export const locationBugs = [
  { value: 'all', label: 'select locations' },
  { value: 'Flying', label: 'Flying' },
  { value: 'Flying near hybrid flowers', label: 'Flying near hybrid flowers' },
  { value: 'Flying by night', label: 'Flying by night' },
  { value: 'On trees', label: 'On trees' },
  { value: 'On the ground', label: 'On the ground' },
  { value: 'On flowers', label: 'On flowers' },
  { value: 'On white flowers', label: 'On white flowers' },
  { value: 'Shaking trees', label: 'Shaking trees' },
  { value: 'Flying (near water)', label: 'Flying (near water)' },
  { value: 'Underground', label: 'Underground' },
  { value: 'On ponds and rivers', label: 'On ponds and rivers' },
  { value: 'On tree stumps', label: 'On tree stumps' },
  { value: 'On palm trees', label: 'On palm trees' },
  { value: 'Under trees', label: 'Under trees' },
  { value: 'On rotten food', label: 'On rotten food' },
  { value: 'On the beach', label: 'On the beach' },
  { value: 'On beach rocks', label: 'On beach rocks' },
  { value: 'Near trash', label: 'Near trash' },
  { value: 'On villagers', label: 'On villagers' },
  {
    value: 'On rocks and bush (when raining)',
    label: 'On rocks and bush (when raining)',
  },
  { value: 'Hitting rocks', label: 'Hitting rocks' },
];
