export const species = [
  { value: 'all', label: 'select species' },
  { value: 'Alligator', label: 'Alligator' },
  { value: 'Anteater', label: 'Anteater' },
  { value: 'Bear', label: 'Bear' },
  { value: 'Bird', label: 'Bird' },
  { value: 'Bull', label: 'Bull' },
  { value: 'Cat', label: 'Cat' },
  { value: 'Chicken', label: 'Chicken' },
  { value: 'Cow', label: 'Cow' },
  { value: 'Cub', label: 'Cub' },
  { value: 'Deer', label: 'Deer' },
  { value: 'Dog', label: 'Dog' },
  { value: 'Duck', label: 'Duck' },
  { value: 'Eagle', label: 'Eagle' },
  { value: 'Elephant', label: 'Elephant' },
  { value: 'Frog', label: 'Frog' },
  { value: 'Goat', label: 'Goat' },
  { value: 'Gorilla', label: 'Gorilla' },
  { value: 'Hamster', label: 'Hamster' },
  { value: 'Hippo', label: 'Hippo' },
  { value: 'Horse', label: 'Horse' },
  { value: 'Kangaroo', label: 'Kangaroo' },
  { value: 'Koala', label: 'Koala' },
  { value: 'Lion', label: 'Lion' },
  { value: 'Monkey', label: 'Monkey' },
  { value: 'Mouse', label: 'Mouse' },
  { value: 'Octopus', label: 'Octopus' },
  { value: 'Ostrich', label: 'Ostrich' },
  { value: 'Penguin', label: 'Penguin' },
  { value: 'Pig', label: 'Pig' },
  { value: 'Rabbit', label: 'Rabbit' },
  { value: 'Rhino', label: 'Rhino' },
  { value: 'Sheep', label: 'Sheep' },
  { value: 'Squirrel', label: 'Squirrel' },
  { value: 'Tiger', label: 'Tiger' },
  { value: 'Wolf', label: 'Wolf' },
];
